# Generated by Django 3.1.7 on 2021-03-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ota_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='price_id',
            field=models.ManyToManyField(to='ota_app.Room'),
        ),
    ]
