# Generated by Django 3.1.7 on 2021-03-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ota_app', '0002_auto_20210308_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_owner',
        ),
    ]
