# Generated by Django 3.1.7 on 2021-03-15 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ota_app', '0004_auto_20210311_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel_owner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hotel_owner',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='hotel_owner',
            name='last_name',
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotels_owned', to='ota_app.hotel_owner'),
        ),
        migrations.AddField(
            model_name='hotel_owner',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
