# Generated by Django 3.1.7 on 2021-03-15 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ota_app', '0005_auto_20210315_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels_owned', to='ota_app.hotel_owner'),
        ),
    ]
