# Generated by Django 3.1.7 on 2021-03-17 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ota_app', '0007_auto_20210315_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='guest_reservations', to='ota_app.room'),
            preserve_default=False,
        ),
    ]
