# Generated by Django 3.1.7 on 2021-03-17 15:17

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ota_app', '0012_auto_20210317_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(default='x', max_length=1200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='facilities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('concierge-bell', 'Concierge'), ('utensils', 'Restaurant'), ('swimming-pool', 'Pool'), ('umbrella-beach', 'Beach'), ('shuttle-van', 'Shuttle'), ('skiing', 'Skiing'), ('wheelchair', 'Disabled faclities'), ('wifi', 'Wifi'), ('tv', 'TV'), ('cocktail', 'Bar'), ('snowflake', 'Air Conditioning'), ('parking', 'Parking'), ('smoking-ban', 'No smoking'), ('dumbbell', 'Gym')], default=('wheelchair', 'Disabled faclities'), max_length=138),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='street',
            field=models.CharField(default='Wysoka 123', max_length=128),
            preserve_default=False,
        ),
    ]
